version: '3.8'

services:
  web:
    build: .
    container_name: gtm_web_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
